# Generated by Django 4.2.5 on 2023-09-25 09:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='viewing',
            options={'verbose_name': 'Просмотр', 'verbose_name_plural': 'Просмотры'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='users',
        ),
        migrations.AddField(
            model_name='product',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Пользователи'),
        ),
    ]
